# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = industrialVision
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lMvCameraControl \
    -lopencv_world440d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(industrialVision.pri)
win32:RC_FILE = industrialVision.rc
